// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: pb/test_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestReq) Reset() {
	*x = TestReq{}
	mi := &file_pb_test_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestReq) ProtoMessage() {}

func (x *TestReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_test_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestReq.ProtoReflect.Descriptor instead.
func (*TestReq) Descriptor() ([]byte, []int) {
	return file_pb_test_message_proto_rawDescGZIP(), []int{0}
}

func (x *TestReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TestResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestResp) Reset() {
	*x = TestResp{}
	mi := &file_pb_test_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResp) ProtoMessage() {}

func (x *TestResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_test_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResp.ProtoReflect.Descriptor instead.
func (*TestResp) Descriptor() ([]byte, []int) {
	return file_pb_test_message_proto_rawDescGZIP(), []int{1}
}

func (x *TestResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_pb_test_message_proto protoreflect.FileDescriptor

const file_pb_test_message_proto_rawDesc = "" +
	"\n" +
	"\x15pb/test_message.proto\x12\x05proto\"\x1d\n" +
	"\aTestReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x1c\n" +
	"\bTestResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msgB\x8a\x01\n" +
	"\tcom.protoB\x10TestMessageProtoP\x01Z7github.com/JrMarcco/easy-rpc/internal/integration/pb/pb\xa2\x02\x03PXX\xaa\x02\x05Proto\xca\x02\x05Proto\xe2\x02\x11Proto\\GPBMetadata\xea\x02\x05Protob\x06proto3"

var (
	file_pb_test_message_proto_rawDescOnce sync.Once
	file_pb_test_message_proto_rawDescData []byte
)

func file_pb_test_message_proto_rawDescGZIP() []byte {
	file_pb_test_message_proto_rawDescOnce.Do(func() {
		file_pb_test_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_test_message_proto_rawDesc), len(file_pb_test_message_proto_rawDesc)))
	})
	return file_pb_test_message_proto_rawDescData
}

var file_pb_test_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_test_message_proto_goTypes = []any{
	(*TestReq)(nil),  // 0: proto.TestReq
	(*TestResp)(nil), // 1: proto.TestResp
}
var file_pb_test_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_test_message_proto_init() }
func file_pb_test_message_proto_init() {
	if File_pb_test_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_test_message_proto_rawDesc), len(file_pb_test_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_test_message_proto_goTypes,
		DependencyIndexes: file_pb_test_message_proto_depIdxs,
		MessageInfos:      file_pb_test_message_proto_msgTypes,
	}.Build()
	File_pb_test_message_proto = out.File
	file_pb_test_message_proto_goTypes = nil
	file_pb_test_message_proto_depIdxs = nil
}
